default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: postgres://sistema_pds_user:oUTvBTFqQR5qVtbDdkqd0HEGO20WJFvW@dpg-csjusrm8ii6s73d8qet0-a.oregon-postgres.render.com/sistema_pds